### ISSUE TITLE
Overture feature: add support for Word sources

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#18]
Overture has a (little used) feature, reflected in the underlying VDMJ code, where you can write a specification that is embedded in an MS Word .doc or .docx file. The parser extracts source from between `%%VDM%%` markers, ignores any Word formatting and then behaves as though it is a regular source file - so you can embed a spec inside a nicely formatted document that describes its purpose.

The Overture editor allows a (read only) version of such specifications to be opened, which just displays the extracted text.

In principle other formats would work, like LaTeX source and ODF (LibreOffice) files. VDMJ supports these, though Overture cannot display ODF.

**Comment by FrederikPM** [comment]
Do we have an example of embedding VDM in word? I cant seem to find how to do this in Overture.
Is anything needed on the VDMJ/LSP side or is it simply a matter of reacting to .doc/.docx files on the client side and stream them to the server?

**Comment by nickbattle** [comment]
Yes, I'll attach my test project below.  There are three binary formats that Overture understands: *.doc, *.docx and *.odt. If you look at BacktrackInputReader's readerFactory method, you can see how these are parsed. The stream reader chosen is based on the filename extension, defaulting to LatexStreamReader which can cope with all the plain text formats (and #ifdefs).

The equivalent of `\begin{vdm_al}` and `\end{vdm_al}` in Word or OpenOffice is `%%VDM%%`. The parser should ignore formatting, so you ought to be able to add this tag and make it invisible (or white or whatever). Similarly, formatting in the VDM source should be ignored, so you can highlight parts if you wish.

If you open the project below in Overture, you should be able to see _read only_ files that only show the VDM parts (ie. the Word content around them is ignored). It has to be read only because editing Word or ODT files is obviously difficult. I assume Overture calls VDMJ directly to do this, but I'm not sure.

I don't know the best architectural way to implement this in LSP. VDMJ (the Server) has the parsing capability. But currently I think (say) *.docx files will be ignored in the Server file scan (which is only *.vdmsl or whatever).

We could perhaps create temporary *.vdmsl files via a new "translate" option? Not sure. Open to suggestions!

[OpenOffice.zip](https://github.com/jonaskrask/vdm-vscode/files/8324537/OpenOffice.zip)

**Comment by nickbattle** [comment]
I should probably add, this isn't a very important feature of Overture. I'm not aware of anyone who uses it seriously, though the idea (that you can keep your written and formal specifications in the same document) is powerful. For example, the work we are doing with the FMI group may mean that a single Word copy of the FMI Standard could be opened in VSCode and tests run against that.

We might also consider format parsers for other file types, like PDFs.

**Comment by FrederikPM** [comment]
It looks like it is not possible to view doc/docx files in VSCode (I can't find any extension that enables it) and given that it is a little used feature I think that we should just drop it?
Alternatively, we could make a feature that extracts the VDM source code from the doc/docx document(s) to enable working with them in a given project.
There is however multiple PDF viewer extensions available that enables viewing PDFs in VSCode so that could be an alternative.

**Comment by nickbattle** [comment]
Yes, I was assuming that we would have to extract the VDM source before displaying it in an editor (read-only). I'd like to try to work out the LSP/Client architecture for doing this, even if we don't actually do it(!). The trouble is, it doesn't really fit well with the LSP view of the world...

**Comment by FrederikPM** [comment]
Hmm. Would it not be something like:
Somehow make the client aware that a VDM langauge server should be started for a project/workspace folder that contains any file(s) with the supported extensions(doc/docx/odt/pdf). Then send a custom message (translate or similar) to the language server, to make the language server search the project for files with the extensions and extract VDM parts. The language server can then push workspace edits to the client to have it create the needed files and then the language server can push a number of document edits to the client to make it populate the files.

**Comment by leouk** [comment]
Hey folks, 
Couple of points: 

1) literate spec 
Z has(d) the same capability in various tools - proof power, z/eves, czt. It's indeed quite powerful, particularly for "manager" users. I worked on a Circus/Z spec for the US defense people that was 4500pages long (in word/rtf)! The iFacts EU air traffic control spec it about same size and also in RTF. 

2) literate analysis
Isabelle allows similar features. They even go further: they have semantic comments (even proofs!) with anti quotations. That is, you can "tag" the latex (Ie like %%vdm%% or the like) and then get Isabelle to keep your text consistent to your forMal model, which you can "gate" as visible or not. This makes checking the consistency of written text much simpler, and is very powerful. 

These are obviously quite interesting/ involved but worth having (particularly if we already have a form of them). 

Happy to elaborate on any of the above as needed. 

Ps: 
Apologies for the late joining; just figured out GitHub mobile!

**Comment by nickbattle** [comment]
Might it be easier for the Server to create plain `<name>.vdmsl` files when it notices `<name>.doc/.docx/.odt` files in a project, and then send a notification back to the Client that these files are read-only?

(Interesting points, Leo)

**Comment by FrederikPM** [comment]
It does not seem like VSCode has build in functionality to disable editing of a file. If a document is marked as read-only by the OS then, at least with Windows, you get a pop-up after having made edits to such a file and pressed save where you actively have to click override when trying to save the file which in turn disables the read-only property.
If we want to disable editing of those files then we would need to do some trickery with intercepting changes to the file and discarding them. If not, then i guess this would actually be purely server-side functionality as the client can discover new files in the directory added outside of vscode/the LSP protocol.

Yes that's some good points Leo!

**Comment by nickbattle** [comment]
The Server could send back a warning notification if you tried to edit an "extracted" file, if it also does the extraction. It might be useful to edit these files, but a warning would remind you that the changes have to be copied back into the Word/whatever source.

**Comment by FrederikPM** [comment]
Yes we could do it like that. Is the idea then to remove the files after the user closes the editor or are they persisted (possibly together with the knowledge that they were generated from the non-VDM file(s))?
If the server is to keep track of the extracted files and whether they are being edited, then we could use the [ShowMessage Notification](https://microsoft.github.io/language-server-protocol/specification#window_showMessage) from the server to display a warning message in the editor.
If the client is to keep track of it we would need to come up with an alternative request that the server can send to the client that informs of the extracted files.

**Comment by nickbattle** [comment]
Hmm, good point. Deleting them on editor-close would be a nuisance, especially if they had been edited in anticipation of updating the Word docs. We could maybe do it on "session close" (ie. Server shutdown). The server should send that notification once per file, I'd say, to avoid annoying users if they are genuinely updating them.

It's looking like it's easiest for the Server to manage this?

**Comment by nickbattle** [comment]
There are shutdown and exit requests that the Client should send to the server. I know something similar is sent for DAP sessions, though that is different. It looks like these are not sent when you close the Client though. But there are handlers ready for them in the Server, so we could hook the cleanup into them.

**Comment by FrederikPM** [comment]
Great. Then I think, unless we are already doing it (can't remember), we just need to spawn the server process detached from the VSCode process to ensure that the server has time to shut down gracefully.
Then, in addition to the above, I will start looking into sending the shutdown request to server and to handle the ShowMessage Notification from the server if this is not already just baked in to VSCode.

**Comment by nickbattle** [comment]
OK, I've just pushed something for the Server. It's a start...

If you include *.doc/docx/odt files, these will be converted to <name>.<dialect>, so for example "test.doc.vdmsl". That means we'll reduce the likelihood of name clashes. The new files don't immediately appear(?) - it seems to need a refresh to see them? But after that you can open the generated files as normal. If you try to edit one, you get a warning notification (once only).

The files are rebuilt when the tree of the project is re-read, which is on file or directory deletion. Creating new files is fine, though creating new doc files may cause problems... not sure.

Have a look/play (on "development" branch).

**Comment by nickbattle** [comment]
I've just pushed some more improvements. You can add/edit Word files in a project now, but it will only extract the VDM "once", so if you have extracted the VDM and edited it, that changed file is retained. If you delete an extracted file, then it will be regenerated from the Word.

You get _one warning_ when you first edit an extracted file. You will always get a second warning if you _save_ those changes.

We're still missing the cleanup, because there is no shutdown message. But the extracted files are fine if you come back later - they are just normal files in the folder, after all. Cleanup is difficult anyway, because you would lose changes that you might want to keep. Not sure how to deal with that...? I'd have to keep a list of unmodified generated files *sigh*.

I was thinking of adding an automatic comment header at the start of the extract files, perhaps saying which doc file it was created from and when.

So it's not quite perfect, but I think it's usable :-)

**Comment by FrederikPM** [comment]
I have had a look at it. On my end the extracted files appear in the explorer panel pretty much immediately when the server is started for a folder. The same is also true for adding a new docx file to an open folder in the explorer panel (with the server already running). 
If I change the VDM source in the docx file I need to force a re-read of the project tree to extract the new source. Although it seems like the client does send a `workspace/didChangeWatchedFiles` notification to the server whenever the docx file changes.
Additionally I seem to get the "Overwriting" warning on subsequent saves after the first.
Lastly, should the message icon be changed from an error (1) to warning (2)?

So I'm not sure if this would be a too inefficient solution. But to avoid losing changes on cleanup we could make it so that the first time the user saves edits to an extracted file it is saved as a new file with something like the prefix 'modified' and then either extract the files from the word source again or recreate the given file from a list of unmodified files. Then we could override any subsequent saved changes to the non modified file and send a warning message to the user saying that the modified file should be edited instead.

Looking at the server log it seems that the server receives a shutdowm message when exiting VSCode, but then the server logs `ERROR: LSP Server stopped`. Does that indicate that its process is killed before being able to gracefully shutdown?
Here's the end of the log:
~~
10:02:32.111: [FINE][1] >>> LSP {"jsonrpc":"2.0","id":12,"method":"shutdown"}
10:02:32.112: [FINE][1] <<< LSP { "jsonrpc" : "2.0", "result" : null, "id" : 12 }
10:02:32.134: [INFO][1] End of stream detected
10:02:32.134: [SEVERE][1] ERROR: LSP Server stopped
~~

**Comment by nickbattle** [comment]
Thanks for trying it :)

Yes, if you change the docx (say) the update is sent to the server, but because it sees an existing extract file,  it doesn't overwrite it (because you may have changed it). If you want the extract to be rebuilt from the docx, the easiest thing is to delete the extract file and it should be rebuilt immediately from the docx.

We could get too clever about this and try to work out when/whether files have actually changed, but I'd prefer to keep it simple if that's workable for people.

I tried to make the editing warning once-only, but the saving warning every time - it's a pain to continually be warning while you're editing, but it's reasonable to get it on a save, which is less often. Yes, I'll convert them both to warnings, sorry! (I forgot what that argument was for!!).

Interesting about the shutdown. That "error" is just to make sure the message is logged, which probably isn't necessary. It does complete the shutdown call. I can downgrade it to INFO. Currently the shutdown handler isn't doing anything serious, so I'll try to enhance that to clean up the extracted files... but again, we need to be careful because they might have changed. Hmm... I need an efficient way to know about updates. I'll let you know :)

**Comment by FrederikPM** [comment]
I thought I had to enable sending the message but I discovered that it was apparently already being send. I can see that the server reacts to the shutdown event, however testing with the OpenOffice project that you send, I see that the server does not delete the `test.doc.vdmsl` file if I have opened it in the editor (without making any edits of course).

**Comment by nickbattle** [comment]
Unless it's a Windows/Linux difference? :(

The cleanup is based on the modification time, compared to the file's creation time. In Linux, an unaltered file has the same creation and modification times. I wonder whether it's different on Windows (I'm assuming you're Windows?). Or it may be that Windows doesn't set the creation time.

Do the extracted files get deleted at shutdown if you don't open them?

**Comment by nickbattle** [comment]
I've just pushed a tweak to change it to use lastModifiedTime for both recording and comparison. Is that any better? (on the right issue this time!)

**Comment by FrederikPM** [comment]
Yes that did the trick! :)

**Comment by nickbattle** [comment]
OK, that's good. This test class may help in future... but filesystems are notoriously difficult with these things!
```
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.attribute.BasicFileAttributes;

public class Test
{
	public static void main(String[] args) throws IOException
	{
		File file = new File(args[0]);
		BasicFileAttributes attr = Files.readAttributes(file.toPath(), BasicFileAttributes.class);
		
		System.out.println("lastModifiedTime = " + attr.lastModifiedTime());
		System.out.println("creationTime = " + attr.creationTime());
	}
}

```

**Comment by FrederikPM** [comment]
I have tried the changes in a Linux VM and it does indeed seem like the shutdown request is not send to the server in that environment for some reason. I will look into this and figure out a solution.

**Comment by nickbattle** [comment]
My version of VSCode is:
```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.15-1-default
```
The VDM extension is a 1.3.3 that you built for a recent feature (can't remember which one!), but it's only a week or so old.

**Comment by nickbattle** [comment]
Ha! Crossed in the post... OK, thanks very much, that explains it.

**Comment by nickbattle** [comment]
I've just extended VDMJ and the Server a little to allow an arbitrary format reader to be plugged into the system. The readers have to implement a new interface called `ExternalFormatReader`, which requires them to produce an `InputStreamReader` that contains the extracted source. The VDMJ examples project has been extended with an example PDF reader that just uses the `pdftotext` command to extract text from a PDF file (works on Linux at least!).

To plug these into the system you set a property (vdmj.parser.externalreaders) which is a CSV list of `<suffix>=<class>` entries, like `.pdf=examples.parser.PDFStreamReader`. You also have to add your parser to the classpath, of course.

Seems to work :-)

**Comment by FrederikPM** [comment]
Great! I guess that the `vdmj.parser.externalreaders` property would be included as part of the VDMJ properties that we discussed making a UI for in #54 .
I have pushed changes to [fpm/18](https://github.com/jonaskrask/vdm-vscode/actions/runs/2050776707) that should enable the extension to send the shutdown request to the server on Linux.
Short of making a dedicated "mark this as a VDM folder" button, I'm not sure how we could start the server on a folder that contains only 'extractable' file format(s) and no VDM file(s). At the moment I just trigger the server to start by including an empty VDM file in the project. But if this is not a hugely used feature I guess that might also be fine for now?

**Comment by nickbattle** [comment]
Yes, that new property ought to be in the "VDMJ properties" UI thing. We don't add new ones that often, I promise! :-)

I'll take a look at that shutdown version, thanks.

Yeah, good point about "pure" extractable document folders. As you say, it's not a hugely used feature so creating an empty file isn't too onerous at the moment.

**Comment by FrederikPM** [comment]
Can this be merged into development?

**Comment by nickbattle** [comment]
I think the logic to do with (not) overwriting files etc is fine. I still can't get the shutdown message to work on Linux though - I'm using the build that I was testing for the "properties" and debug launch bug. Should that be working? I'm just not getting the request (this is in debug, though the extracted files don't get deleted even when not debugging).

**Comment by FrederikPM** [comment]
It should be [this build](https://github.com/jonaskrask/vdm-vscode/actions/runs/2050776707) that enables to send the shutdown message on Linux.

**Comment by nickbattle** [comment]
Right, that shutdown now works, thanks.

It can get a bit confusing when the extracted files get deleted, but I think it does all work. The surprising case is if an extract exists when you open the project, it will be regarded as "modified" and not cleaned up at the end. I've been getting that a lot because I was running a version that didn't do shutdown clean-ups! But usually this should be fine: the only time the files are left there is if you changed them, and thereafter they are safe until you delete them by hand.

So, I think we're done on this one, yes.

**Comment by FrederikPM** [comment]
Great! Thanks for giving it a go. I'll merge it into development :)
